### ISSUE TITLE
enet-Adapter  - keine Verbindung weil: kann Adapter nicht finden 

### ISSUE THREAD

**Issue by ruebenkraut** [stoffel7/ioBroker.enet#54]
Hallo 
der enet-Adapter, der bei mir auf eine Gateway zugreifen soll, bekommt laut Fehlerprotokoll keine Verbindung.
In der Einstellung habe ich jedoch nur die Möglichkeit die IP-Adresse einzugeben.
Gateway und IObroker befinden sich im gleichen Netz.

Das Gateway kann ich auch problemlos über die Handy-App steuern.
Was mache ich hier falsch?

******************
enet.0 | 2023-10-13 07:47:06.099 | error | Cannot read properties of undefined (reading 'common')
-- | -- | -- | --
enet.0 | 2023-10-13 07:47:06.099 | error | TypeError:  Cannot read properties of undefined (reading 'common')    at new  Adapter  (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:8480:47)     at startAdapter  (/opt/iobroker/node_modules/iobroker.enet/main.js:65:15)    at  Object.<anonymous>  (/opt/iobroker/node_modules/iobroker.enet/main.js:33:5)    at  Module._compile (node:internal/modules/cjs/loader:1256:14)    at  Module._extensions..js (node:internal/modules/cjs/loader:1310:10)    at  Module.load (node:internal/modules/cjs/loader:1119:32)    at  Module._load (node:internal/modules/cjs/loader:960:12)    at  Function.executeUserEntryPoint [as runMain]  (node:internal/modules/run_main:81:12)    at  node:internal/main/run_main_module:23:47
enet.0 | 2023-10-13 07:47:06.097 | error | uncaught exception: Cannot read properties of undefined (reading 'common')
host.debian | 2023-10-13 07:47:05.664 | info | instance system.adapter.enet.0 started with pid 6403
host.debian | 2023-10-13 07:47:04.650 | info | Restart adapter system.adapter.enet.0 because enabled
host.debian | 2023-10-13 07:47:04.650 | error | instance system.adapter.enet.0 terminated with code 10 (CANNOT_FIND_ADAPTER_DIR)
enet.0 | 2023-10-13 07:47:04.273 | info | starting. Version 1.0.1 in /opt/iobroker/node_modules/iobroker.enet, node: v18.17.1, js-controller: 4.0.24
*****************

**Comment by stoffel7** [comment]
get es um das USB Gateway oder den ENET-Server

**Comment by stoffel7** [comment]
besteht das Problem noch?
